# create the environment from this file with `conda env create -f conda_env.yml`
name: gp
channels:
  - conda-forge
dependencies:
  - pybind11
  - pandas
  - numpy=1.21.4
  - matplotlib
  - pytest
  - cxx-compiler
  - make
  - cmake
  - eigen
