name: build


on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
    schedule:
      # Run every Sunday at midnight
      - cron:  '0 0 * * 0'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: gp
          environment-file: environment.yml
          init-shell: bash
          cache-environment: false
          cache-downloads: true

      - name: List environment
        shell: bash
        run: |
          eval "$(micromamba shell hook --shell=bash)"
          micromamba activate gp
          micromamba list

      - name: Configure and compile the library
        shell: bash
        run: |
          eval "$(micromamba shell hook --shell=bash)"
          micromamba activate gp
          mkdir build && cd build
          cmake -DCMAKE_VERBOSE_MAKEFILE=yes -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX ..
          make all install

      - name: Install via pip
        shell: bash
        run: |
          eval "$(micromamba shell hook --shell=bash)"
          micromamba activate gp
          pip install -vv .

      - name: Verify import of python class
        shell: bash
        run: |
          eval "$(micromamba shell hook --shell=bash)"
          micromamba activate gp
          pytest -sv tests/test_import.py
          cd tests/
          pytest -sv test_import.py
          cd ..

      - name: Run demo
        shell: bash
        run: |
          eval "$(micromamba shell hook --shell=bash)"
          micromamba activate gp
          cd demo
          python demo.py
          python sensor_demo.py
          cd ..