name: build


on:
    push:
      branches: [ cmake ]
    # pull_request:
    #   branches: [ main ]
    schedule:
      # Run every Sunday at midnight
      - cron:  '0 0 * * 0'

jobs:


  build_intel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Mamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        cache-environment: false
        cache-downloads: true
        
    - name: List environment
      run: |
        micromamba activate
        micromamba list

    - name: Configure and compile the library
      run: |
        mkdir build && cd build
        cmake -DCMAKE_VERBOSE_MAKEFILE=yes -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX ..
        make all install


    - name: Install via pip
      run: |
          pip install -vv .
          shell: bash -el {0}