name: coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies using conda
      - name: Set up Conda environment
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
          bash Miniforge3-Linux-x86_64.sh -b -p $HOME/miniforge
          source $HOME/miniforge/bin/activate
          conda env create -f environment.yml
          conda activate gp
          conda install pytest pytest-cov codecov -y

      # Run tests with coverage
      - name: Run tests and calculate coverage
        run: |
          source $HOME/miniforge/bin/activate
          conda activate FastGaussianPuff
          pytest --cov=fast_gaussian_puff tests/

      # Upload coverage report to Codecov
      - name: Upload coverage to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          source $HOME/miniforge/bin/activate
          conda activate gp
          codecov
